// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package ccccc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AaaaClient is the client API for Aaaa service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AaaaClient interface {
	SayHello1111(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type aaaaClient struct {
	cc grpc.ClientConnInterface
}

func NewAaaaClient(cc grpc.ClientConnInterface) AaaaClient {
	return &aaaaClient{cc}
}

func (c *aaaaClient) SayHello1111(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/ddsdfsd.ccccc.aaaa/SayHello1111", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AaaaServer is the server API for Aaaa service.
// All implementations must embed UnimplementedAaaaServer
// for forward compatibility
type AaaaServer interface {
	SayHello1111(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedAaaaServer()
}

// UnimplementedAaaaServer must be embedded to have forward compatible implementations.
type UnimplementedAaaaServer struct {
}

func (UnimplementedAaaaServer) SayHello1111(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello1111 not implemented")
}
func (UnimplementedAaaaServer) mustEmbedUnimplementedAaaaServer() {}

// UnsafeAaaaServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AaaaServer will
// result in compilation errors.
type UnsafeAaaaServer interface {
	mustEmbedUnimplementedAaaaServer()
}

func RegisterAaaaServer(s grpc.ServiceRegistrar, srv AaaaServer) {
	s.RegisterService(&Aaaa_ServiceDesc, srv)
}

func _Aaaa_SayHello1111_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AaaaServer).SayHello1111(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ddsdfsd.ccccc.aaaa/SayHello1111",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AaaaServer).SayHello1111(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Aaaa_ServiceDesc is the grpc.ServiceDesc for Aaaa service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Aaaa_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ddsdfsd.ccccc.aaaa",
	HandlerType: (*AaaaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello1111",
			Handler:    _Aaaa_SayHello1111_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aaaa.proto",
}
